### ISSUE TITLE
Sounds Great!!!

### ISSUE THREAD

**Issue by MauroNigrele** [EcomDev/EcomDev_LayoutCompiler#1]
Hi Ivan, the idea sounds great how can i contribute?

**Comment by IvanChepurnyi** [comment]
Hi @MauroNigrele, I almost finished the extension already, there left very small part for it. You could really help in doing benchmarks comparing it with standard Magento implementation. Also I probably need a help with documenting the extension, like user manual, etc.

**Comment by IvanChepurnyi** [comment]
Please do not hesitate to create manuals in docs/ directory for extension ;)
