### ISSUE TITLE
Symfony filesystem dependency breaks PHP 5.4 compatibility

### ISSUE THREAD

**Issue by peterjaap** [EcomDev/EcomDev_LayoutCompiler#10]
`"symfony/filesystem": ">2.3"`

This requires at least PHP 5.5.9, see [here](https://github.com/symfony/filesystem/blob/master/composer.json).

Use tag 1.0.0 if that is the case for you.

This should at the very least be reflected in the README, which still states 5.4 as the minimum PHP version.

**Comment by IvanChepurnyi** [comment]
seems like I will remove that dependency.

**Comment by IvanChepurnyi** [comment]
Fixed in develop branch, will be released later today.
