### ISSUE TITLE
Flushing compiler cache

### ISSUE THREAD

**Issue by paales** [EcomDev/EcomDev_LayoutCompiler#4]
Is it me or isn't it possible to flush the compiler cache? Ideally it should be flushed when the layout cache is flushed?

**Comment by IvanChepurnyi** [comment]
You can manully delete all var/ecomdev/layoutcompiler directory for invalidating all compiler files. But it re-validates checksum every 3600 seconds on production if layout cache is turned on and if you refresh layout cache, it revalidates file checksum.
