### ISSUE TITLE
Crash front

### ISSUE THREAD

**Issue by artmouse** [EcomDev/EcomDev_LayoutCompiler#5]
If enable Compile Layout design crashed. How to debug this issue?

**Comment by IvanChepurnyi** [comment]
Can you tell more about your issue?

**Comment by artmouse** [comment]
Custom theme. Some CSS missing if Compile Layout enabled.

**Comment by IvanChepurnyi** [comment]
Can ellaborate more about what is your crash report and so on?

**Comment by IvanChepurnyi** [comment]
I cannot fix an issue, if there is not enough of the data

**Comment by IvanChepurnyi** [comment]
As no answer has been provided for 6 months, issue gets closed
