### ISSUE TITLE
Widgets not rendering

### ISSUE THREAD

**Issue by paales** [EcomDev/EcomDev_LayoutCompiler#6]
When enabling the layout compiler the widgets aren't rendered anymore.

**Comment by IvanChepurnyi** [comment]
Can you provide more details? 
Is it instance widgets or inline widgets? What is the widget configuration?

**Comment by paales** [comment]
@IvanChepurnyi I haven't been able to set up a testcase yet.. Will let you know when I do.

**Comment by IvanChepurnyi** [comment]
Hey Paul (@paales), do you have any news on this?

**Comment by paales** [comment]
@IvanChepurnyi Sorry, haven't had time to check it any more. We disabled the module, performance was ok.
