### ISSUE TITLE
Weird path when installing through Composer

### ISSUE THREAD

**Issue by erfanimani** [EcomDev/EcomDev_LayoutCompiler#7]
There is a weird bug happening (I've seen it often on various dev environments) where the path to the module isn't quite right.

I think it's got something to do with the wildcards used in the modman file: https://github.com/EcomDev/EcomDev_LayoutCompiler/blob/master/modman

I've never seen wildcards used before in such a way (or in composer.json Magento mapping) and suspect a bug is happening with this module in combination with the Magento hackathon composer installer.

The path that it tries to install is:

`app/code/community/EcomDev/LayoutCompiler/LayoutCompiler/LayoutCompiler/Helper/Data.php` (LayoutCompiler is there three times).

![image](https://cloud.githubusercontent.com/assets/930470/12372897/2df353b8-bca2-11e5-97b9-330c3c74775b.png)

I can replicate it consistently by running `composer.phar run-script post-install-cmd -vvv -- --redeploy`.

I might investigate further and do a PR.

**Comment by IvanChepurnyi** [comment]
Are you using the right composer installer at the right version? The one that is at https://github.com/Cotya/magento-composer-installer is the only supported one.

I cannot reproduce this issue with a composer installer.
